#!/usr/bin/env python3
"""Bundle Firmware/web into a C++ PROGMEM header for ESP8266WebServer.

The web source remains editable as normal HTML/CSS/JS. PlatformIO runs this
script before compilation and regenerates src/generated/web_assets.h.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_DIR = ROOT / "web"
OUT_DIR = ROOT / "src" / "generated"
OUT_FILE = OUT_DIR / "web_assets.h"

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
}

ASSETS = [
    ("index", "/", WEB_DIR / "index.html"),
    ("styles", "/styles.css", WEB_DIR / "styles.css"),
    ("app", "/app.js", WEB_DIR / "app.js"),
]


def cpp_raw_literal(text: str) -> str:
    marker = "WEB_ASSET"
    while f"){marker}\"" in text:
        marker += "_"
    return f'R"{marker}({text}){marker}"'


def symbol(name: str, suffix: str) -> str:
    return f"WEB_ASSET_{name.upper()}_{suffix}"


def main() -> None:
    missing = [str(path.relative_to(ROOT)) for _, _, path in ASSETS if not path.exists()]
    if missing:
        raise SystemExit(f"Missing web asset(s): {', '.join(missing)}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by scripts/generate_web_assets.py. Do not edit by hand.",
        "// Edit files under Firmware/web/ instead.",
        "",
    ]

    for name, _, path in ASSETS:
        content = path.read_text(encoding="utf-8").strip() + "\n"
        lines.append(f"const char {symbol(name, 'CONTENT')}[] PROGMEM = {cpp_raw_literal(content)};")
        lines.append("")

    lines.extend([
        "struct WebAsset {",
        "    const char* path;",
        "    const char* contentType;",
        "    const char* content;",
        "};",
        "",
        "const WebAsset WEB_ASSETS[] = {",
    ])

    for name, route, path in ASSETS[1:]:
        content_type = CONTENT_TYPES.get(path.suffix, "text/plain; charset=utf-8")
        lines.append(f'    {{"{route}", "{content_type}", {symbol(name, "CONTENT")}}},')

    lines.extend([
        "};",
        "",
        "const size_t WEB_ASSET_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);",
        "",
    ])

    new_content = "\n".join(lines)
    old_content = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.exists() else None
    if new_content != old_content:
        OUT_FILE.write_text(new_content, encoding="utf-8")
        print(f"Generated {OUT_FILE.relative_to(ROOT)}")
    else:
        print(f"Generated {OUT_FILE.relative_to(ROOT)} (unchanged)")


if __name__ == "__main__":
    main()
