#!/usr/bin/env python3
"""Generate the 32x32 XBM home icons for the v2 UI.

Draws the icons with Pillow and emits src/generated/app_icons.h
(XBM layout: row-major, LSB-first, 4 bytes per row). A scaled preview
PNG is written next to this script for visual inspection.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "src" / "generated"
PREVIEW = Path(__file__).resolve().parent / "app_icons_preview.png"
SIZE = 32


def new_canvas() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    img = Image.new("1", (SIZE, SIZE), 0)
    return img, ImageDraw.Draw(img)


def washer_icon() -> Image.Image:
    """滚筒洗衣机：机身 + 面板旋钮 + 圆形舱门。"""
    img, d = new_canvas()
    d.rounded_rectangle([3, 1, 28, 30], radius=4, outline=1, width=2)
    d.line([5, 9, 26, 9], fill=1, width=1)
    d.ellipse([5, 4, 8, 7], fill=1)          # 左旋钮
    d.ellipse([11, 4, 14, 7], fill=1)        # 右旋钮
    d.ellipse([8, 12, 24, 28], outline=1, width=2)   # 舱门
    d.ellipse([14, 18, 18, 22], outline=1, width=1)  # 舱门内圈
    return img


def info_icon() -> Image.Image:
    """圆形徽标 i：信息页入口。"""
    img, d = new_canvas()
    d.ellipse([2, 2, 29, 29], outline=1, width=2)
    d.ellipse([14, 7, 17, 10], fill=1)
    d.line([16, 13, 16, 23], fill=1, width=3)
    return img


def to_xbm_bytes(img: Image.Image) -> list[int]:
    pixels = img.load()
    data: list[int] = []
    for y in range(SIZE):
        for x0 in range(0, SIZE, 8):
            byte = 0
            for bit in range(8):
                if pixels[x0 + bit, y]:
                    byte |= 1 << bit
            data.append(byte)
    return data


def ascii_art(img: Image.Image) -> str:
    pixels = img.load()
    return "\n".join(
        "".join("#" if pixels[x, y] else "." for x in range(SIZE))
        for y in range(SIZE)
    )


def main() -> None:
    icons = [("app_icon_washer", washer_icon()), ("app_icon_info", info_icon())]

    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/* Generated by scripts/generate_icons.py. Do not edit by hand.",
        " * 32x32 XBM, row-major, LSB-first (128 bytes per icon). */",
        "",
    ]
    for name, img in icons:
        data = to_xbm_bytes(img)
        rows = [", ".join(f"0x{byte:02x}" for byte in data[i : i + 8]) for i in range(0, 128, 8)]
        body = ",\n    ".join(rows)
        lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
        lines.append(f"    {body}")
        lines.append("};")
        lines.append("")
        print(f"== {name} ==")
        print(ascii_art(img))
        print()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "app_icons.h").write_text("\n".join(lines), encoding="utf-8")

    sheet = Image.new("1", (SIZE * len(icons) * 10, SIZE * 10), 0)
    for index, (_, img) in enumerate(icons):
        big = img.resize((SIZE * 10, SIZE * 10), Image.NEAREST)
        sheet.paste(big, (index * SIZE * 10, 0))
    sheet.save(PREVIEW)
    print(f"Wrote {OUT_DIR / 'app_icons.h'}")
    print(f"Preview: {PREVIEW}")


if __name__ == "__main__":
    main()
