#!/usr/bin/env python3
"""Generate the u8g2 font subsets used by the v2 UI.

Scans the app sources for string literals to collect the exact charset the
interface renders, then requests WenQuanYi subsets from the LEDFont Agent API
(https://ledfont.botelvdong.com). Emits src/generated/kk_app_font.h/.c plus a
font-resources.json provenance record.

Run again after changing any UI text; the committed generated files stay
valid until then.
"""

from __future__ import annotations

import datetime
import json
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

BASE_URL = "https://ledfont.botelvdong.com"
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT_DIR = SRC / "generated"
SCAN_FILES = [SRC / "washer_app.c", SRC / "washer.cpp", SRC / "main.cpp"]
EXTRA_CHARS = " 0123456789.-%:/"
FONTS = [
    ("kk_font_app_title", "wenquanyi_9pt", 12),
    ("kk_font_app_body", "wenquanyi_13px", 14),
]

HEADER_TEMPLATE = """#pragma once

#include <stdint.h>

/* Generated by scripts/generate_font.py via LEDFont Agent API v1.
 * Do not edit by hand; regenerate after changing UI text. */

#ifdef __cplusplus
extern "C" {{
#endif

{externs}

#ifdef __cplusplus
}}
#endif
"""

ESCAPES = {"n": "\n", "t": "\t", "r": "\r", "0": "\0", '"': '"', "\\": "\\", "'": "'"}


def collect_characters() -> str:
    chars = set(EXTRA_CHARS)
    literal = re.compile(r'"((?:[^"\\\n]|\\.)*)"')
    for path in SCAN_FILES:
        text = path.read_text(encoding="utf-8")
        for raw in literal.findall(text):
            index = 0
            while index < len(raw):
                ch = raw[index]
                if ch == "\\" and index + 1 < len(raw):
                    index += 1
                    ch = ESCAPES.get(raw[index], raw[index])
                if ch >= " ":  # 换行等控制字符不参与排版。
                    chars.add(ch)
                index += 1
    return "".join(sorted(chars))


def http_json(request: urllib.request.Request) -> dict:
    with urllib.request.urlopen(request, timeout=90) as response:
        return json.loads(response.read().decode("utf-8"))


def get_catalog() -> dict[str, dict]:
    request = urllib.request.Request(
        BASE_URL + "/api/v1/compressed-fonts",
        headers={"Accept": "application/json"},
    )
    payload = http_json(request)
    return {item["id"]: item for item in payload["data"]}


def size_supported(spec: dict, size: int) -> bool:
    if "sizes" in spec:
        return size in spec["sizes"]
    bounds = spec.get("size", {})
    return bounds.get("min", size) <= size <= bounds.get("max", size)


def generate_font(font_id: str, size: int, text: str, array_name: str) -> dict:
    body = json.dumps(
        {"font": font_id, "size": size, "text": text, "array_name": array_name}
    ).encode("utf-8")
    for _ in range(5):
        request = urllib.request.Request(
            BASE_URL + "/api/v1/compressed-fonts/generate",
            data=body,
            headers={"Content-Type": "application/json", "Accept": "application/json"},
        )
        try:
            payload = http_json(request)
        except urllib.error.HTTPError as err:
            if err.code == 429:
                wait = int(err.headers.get("Retry-After", "10"))
                print(f"rate limited, retrying in {wait}s")
                time.sleep(wait)
                continue
            raise SystemExit(f"LEDFont error {err.code}: {err.read().decode('utf-8', 'replace')}")
        return payload["data"]
    raise SystemExit("LEDFont kept rate limiting, give up")


def main() -> None:
    catalog = get_catalog()
    for _, font_id, size in FONTS:
        if font_id not in catalog:
            raise SystemExit(f"font {font_id} not in catalog: {sorted(catalog)}")
        if not size_supported(catalog[font_id], size):
            raise SystemExit(f"font {font_id} does not support size {size}")

    text = collect_characters()
    print(f"charset ({len(text)} chars): {text}")

    resources = {
        "source": BASE_URL + "/agent-api.md",
        "generated_at": datetime.date.today().isoformat(),
        "fonts": [],
    }
    c_parts = [
        "/* Generated by scripts/generate_font.py via LEDFont Agent API v1.",
        " * Do not edit by hand; regenerate after changing UI text. */",
        "",
        '#include "kk_app_font.h"',
        "",
    ]
    for array_name, font_id, size in FONTS:
        data = generate_font(font_id, size, text, array_name)
        if data["array_name"] != array_name or data["glyph_count"] < 1:
            raise SystemExit(f"unexpected response for {array_name}: {json.dumps(data)[:400]}")
        print(f"{array_name}: {data['glyph_count']} glyphs, {data['byte_count']} bytes")
        c_parts.append(f"/* Font: {font_id}; Size: {size}; Glyphs: {data['glyph_count']} */")
        c_parts.append(data["c_source"])
        c_parts.append("")
        resources["fonts"].append(
            {
                "array_name": array_name,
                "font": font_id,
                "size": size,
                "characters": data["characters"],
                "glyph_count": data["glyph_count"],
                "byte_count": data["byte_count"],
            }
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "kk_app_font.c").write_text("\n".join(c_parts), encoding="utf-8")
    externs = "\n".join(f"extern const uint8_t {name}[];" for name, _, _ in FONTS)
    (OUT_DIR / "kk_app_font.h").write_text(
        HEADER_TEMPLATE.format(externs=externs), encoding="utf-8"
    )
    (OUT_DIR / "font-resources.json").write_text(
        json.dumps(resources, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote {OUT_DIR / 'kk_app_font.c'} / .h / font-resources.json")


if __name__ == "__main__":
    main()
